using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Net;
using System.Text;
using System.Threading;
using System.Web.Script.Serialization;
namespace SuperRocket64 {
    internal sealed class FakeUpdateTransport : IUpdateTransport {
        internal byte[] Api, Metadata, Executable;
        internal int Reads, Downloads;
        internal bool Offline, PartialCancel, Corrupt;
        internal bool WaitForCancel = false;
        public byte[] Read(Uri uri,int limit,CancellationToken token) {Reads++;while(WaitForCancel&&!token.IsCancellationRequested)Thread.Sleep(20);token.ThrowIfCancellationRequested();if(Offline)throw new WebException("Offline fixture",WebExceptionStatus.ConnectFailure);byte[] data=uri.AbsoluteUri==ReleaseUpdates.Latest?Api:Metadata;Guard.Need(data.Length<=limit,"Fixture oversized");return data;}
        public void Download(Uri uri,string destination,long size,CancellationToken token,Action<long,long> progress) {Downloads++;token.ThrowIfCancellationRequested();File.WriteAllBytes(destination,PartialCancel?new byte[]{1,2,3}:Corrupt?new byte[Executable.Length]:Executable);if(PartialCancel)throw new OperationCanceledException();}
        internal static FakeUpdateTransport New(string version,byte[] executable) {
            var value=new FakeUpdateTransport {Executable=executable};value.Build(version,null,null);return value;
        }
        internal void Build(string version,Action<Dictionary<string,object>> changeManifest,Action<Dictionary<string,object>> changeRelease) {
            var manifest=new Dictionary<string,object>{{"schema",1},{"edition","super-rocket-64"},{"platform","windows-x64"},{"update_protocol",1},{"data_contract",1},{"version",version},{"asset","Super-Rocket-64-Windows-x64.exe"},{"size",Executable.Length},{"sha256",Hash(Executable)},{"payload_sha256",new string('a',64)}};
            if(changeManifest!=null)changeManifest(manifest);Metadata=UpdateJson.Bytes(manifest);
            var assets=new object[]{Asset("Super-Rocket-64-update.json",version,Metadata),Asset("Super-Rocket-64-Windows-x64.exe",version,Executable)};
            var release=new Dictionary<string,object>{{"draft",false},{"prerelease",true},{"tag_name","v"+version},{"assets",assets}};
            if(changeRelease!=null)changeRelease(release);Api=UpdateJson.Bytes(new object[]{release});
        }
        private static object Asset(string name,string version,byte[] bytes) {return new Dictionary<string,object>{{"name",name},{"state","uploaded"},{"size",bytes.Length},{"digest","sha256:"+Hash(bytes)},{"browser_download_url","https://github.com/RyanCraighead/super-rocket-64/releases/download/v"+version+"/"+name}};}
        internal static string Hash(byte[] bytes){using(var stream=new MemoryStream(bytes))return Guard.Hash(stream);}
    }
    internal static class UpdateTests {
        private static string root,fixture;private static int passed;
        private static void Need(bool value,string message){if(!value)throw new Exception(message);}
        private static void Test(string name,Action action){action();passed++;Console.WriteLine("PASS "+name);}
        private static void Reject(Action action){bool failed=false;try{action();}catch(InvalidDataException){failed=true;}catch(IOException){failed=true;}catch(ArgumentException){failed=true;}Need(failed,"Expected rejection");}
        private static string Dir(string name){string path=Path.GetFullPath(Path.Combine(root,name));Directory.CreateDirectory(path);return path;}
        private static ReleasePlan Plan(FakeUpdateTransport transport){return ReleaseUpdates.Check(transport,"0.2.0",CancellationToken.None).Available;}
        private static void MetadataTests(){
            Test("legacy check consent never becomes install consent",delegate {
                string folder=Dir("legacy-preferences");
                File.WriteAllText(UpdatePreferences.PathFor(folder), "{\"schema\":1,\"configured\":true,\"automatic_checks\":true}");
                var prefs=UpdatePreferences.Load(folder);Need(prefs.AutomaticChecks&&!prefs.ModeChosen&&!prefs.AutomaticApply,"Legacy consent escalated");
                prefs.Save(folder);prefs=UpdatePreferences.Load(folder);Need(prefs.AutomaticChecks&&!prefs.AutomaticApply&&!prefs.ModeChosen,"Legacy save escalated consent");
                prefs.ModeChosen=prefs.AutomaticApply=true;prefs.PausedVersion="0.3.0";prefs.Save(folder);
                prefs=UpdatePreferences.Load(folder);Need(prefs.ModeChosen&&prefs.AutomaticApply&&prefs.PausedVersion=="0.3.0","Explicit apply/pause lost");
            });

            byte[] bytes=Encoding.ASCII.GetBytes("synthetic update fixture");
            Test("no public release leaves installation untouched",delegate {var t=FakeUpdateTransport.New("0.3.0",bytes);t.Api=Encoding.UTF8.GetBytes("[]");Need(Plan(t)==null&&t.Reads==1,"No-release behavior");});
            Test("same and older versions never download metadata or downgrade",delegate {foreach(string v in new[]{"0.2.0","0.1.0"}){var t=FakeUpdateTransport.New(v,bytes);Need(Plan(t)==null&&t.Reads==1&&t.Downloads==0,"Downgrade/up-to-date");}});
            Test("published preview uses numeric version and verified GitHub asset digests",delegate {var t=FakeUpdateTransport.New("0.3.0",bytes);var p=Plan(t);Need(p.Version=="0.3.0"&&p.Preview&&p.Sha256==FakeUpdateTransport.Hash(bytes)&&t.Reads==2,"Valid release");});
            Test("draft and unsupported version tags are ignored",delegate {var t=FakeUpdateTransport.New("0.3.0",bytes);t.Build("0.3.0",null,delegate(Dictionary<string,object> r){r["draft"]=true;});Need(Plan(t)==null,"Draft offered");t.Build("0.3.0",null,delegate(Dictionary<string,object> r){r["tag_name"]="v9999-beta";});Need(Plan(t)==null,"Unsupported tag offered");});
            Test("offline and canceled checks do not stage an executable",delegate {var t=FakeUpdateTransport.New("0.3.0",bytes);t.Offline=true;try{Plan(t);throw new Exception("Offline accepted");}catch(WebException){}var c=new CancellationTokenSource();c.Cancel();try{ReleaseUpdates.Check(t,"0.2.0",c.Token);throw new Exception("Cancel accepted");}catch(OperationCanceledException){}Need(t.Downloads==0,"Downloaded while offline");});
            Test("wrong platform edition protocol data version and asset fail closed",delegate {foreach(string key in new[]{"platform","edition","update_protocol","data_contract","version","asset"}){var t=FakeUpdateTransport.New("0.3.0",bytes);t.Build("0.3.0",delegate(Dictionary<string,object> m){m[key]=(key=="update_protocol"||key=="data_contract")?(object)99:"wrong";},null);Reject(delegate{Plan(t);});}});
            Test("manifest truncation or tampering is rejected",delegate {var t=FakeUpdateTransport.New("0.3.0",bytes);t.Metadata[0]=(byte)'!';Reject(delegate{Plan(t);});});
            Test("missing assets and foreign project URLs are rejected",delegate {var t=FakeUpdateTransport.New("0.3.0",bytes);t.Build("0.3.0",null,delegate(Dictionary<string,object> r){r["assets"]=new object[0];});Reject(delegate{Plan(t);});t.Build("0.3.0",null,delegate(Dictionary<string,object> r){var a=(Dictionary<string,object>)((object[])r["assets"])[0];a["browser_download_url"]="https://github.com/Other/repo/releases/download/v0.3.0/Super-Rocket-64-update.json";});Reject(delegate{Plan(t);});});
            Test("only pinned HTTPS API and repository download URLs are initial destinations",delegate {Need(OfficialUpdateTransport.Allowed(new Uri(ReleaseUpdates.Latest),true),"API rejected");Need(OfficialUpdateTransport.Allowed(new Uri("https://github.com/RyanCraighead/super-rocket-64/releases/download/v0.3.0/Super-Rocket-64-Windows-x64.exe"),true),"Asset rejected");foreach(string u in new[]{"http://api.github.com/repos/RyanCraighead/super-rocket-64/releases?per_page=20","https://evil.example/file.exe","https://github.com/Other/repo/releases/download/v0.3.0/Super-Rocket-64-Windows-x64.exe","https://github.com:444/RyanCraighead/super-rocket-64/releases/download/v0.3.0/Super-Rocket-64-Windows-x64.exe","https://release-assets.githubusercontent.com/file.exe"})Need(!OfficialUpdateTransport.Allowed(new Uri(u),true),u);Need(OfficialUpdateTransport.Allowed(new Uri("https://release-assets.githubusercontent.com/github-production-release-asset/1?signature=x"),false),"Official asset CDN rejected");});
            Test("partial download cancellation cleans only its stage and can retry",delegate {var t=FakeUpdateTransport.New("0.3.0",bytes);var p=Plan(t);string folder=Dir("cancel");t.PartialCancel=true;try{ReleaseUpdates.Download(p,folder,t,CancellationToken.None);throw new Exception("Cancel ignored");}catch(OperationCanceledException){}Need(Directory.GetFiles(folder,"*",SearchOption.AllDirectories).Length==0,"Partial left behind");t.PartialCancel=false;string path=ReleaseUpdates.Download(p,folder,t,CancellationToken.None);Need(Guard.HashFile(path)==p.Sha256,"Retry failed");int count=t.Downloads;ReleaseUpdates.Download(p,folder,t,CancellationToken.None);Need(t.Downloads==count,"Verified download not reused");});
            Test("corrupt executable and tampered cache never activate",delegate {var t=FakeUpdateTransport.New("0.3.0",bytes);var p=Plan(t);string folder=Dir("tamper");t.Corrupt=true;Reject(delegate{ReleaseUpdates.Download(p,folder,t,CancellationToken.None);});t.Corrupt=false;string path=ReleaseUpdates.Download(p,folder,t,CancellationToken.None);File.WriteAllText(path,"bad");Reject(delegate{ReleaseUpdates.Download(p,folder,t,CancellationToken.None);});Need(!File.Exists(UpdateStore.StatePath(folder)),"Unexpected activation");});
        }
        private static void StateTests(){
            Test("first-run notification defaults and opt-out persist",delegate {string folder=Dir("preferences");var p=UpdatePreferences.Load(folder);Need(!p.Configured&&p.AutomaticChecks&&!p.AutomaticApply&&!p.DesktopShortcut&&p.StartMenuShortcut,"Wrong defaults");p.Configured=true;p.AutomaticChecks=true;p.DesktopShortcut=true;p.Save(folder);p=UpdatePreferences.Load(folder);Need(p.Configured&&p.AutomaticChecks&&p.DesktopShortcut,"Save failed");p.AutomaticChecks=false;p.Save(folder);Need(!UpdatePreferences.Load(folder).AutomaticChecks,"Disable failed");});
            Test("operation lease prevents concurrent setup game and update",delegate {string folder=Dir("lease");using(var held=OperationLease.Acquire(folder)){Exception result=null;var thread=new Thread(delegate(){try{using(var other=OperationLease.Acquire(folder)){} }catch(Exception e){result=e;}});thread.Start();thread.Join();Need(result is IOException,"Concurrent lease allowed");}using(var next=OperationLease.Acquire(folder)){} });
            Test("failed restart and active-game guard retain exact active pointer and private data",delegate {string folder=Dir("failure");var old=UpdateStore.Capture(folder,fixture,"0.2.0");var next=UpdateStore.Capture(folder,fixture,"0.3.0");UpdateStore.Save(folder,new LauncherState{active=old});string save=Path.Combine(Dir("failure/data"),"user.sav");File.WriteAllText(save,"KEEP");byte[] before=File.ReadAllBytes(UpdateStore.StatePath(folder));Reject(delegate{UpdateStore.Activate(folder,next,delegate{return true;},delegate{return true;});});Need(Convert.ToBase64String(before)==Convert.ToBase64String(File.ReadAllBytes(UpdateStore.StatePath(folder))),"Game guard changed pointer");Reject(delegate{UpdateStore.Activate(folder,next,delegate{return false;},delegate{return false;});});Need(UpdateStore.Load(folder).active.version=="0.2.0"&&File.ReadAllText(save)=="KEEP","Rollback failed");});
            Test("successful activation and rollback preserve both versions and saves",delegate {string folder=Dir("success");var old=UpdateStore.Capture(folder,fixture,"0.2.0");var next=UpdateStore.Capture(folder,fixture,"0.3.0");UpdateStore.Save(folder,new LauncherState{active=old});UpdateStore.Activate(folder,next,delegate{return false;},delegate{return true;});var state=UpdateStore.Load(folder);Need(state.active.version=="0.3.0"&&state.previous.version=="0.2.0","Activation state");UpdateStore.Activate(folder,state.previous,delegate{return false;},delegate{return true;});state=UpdateStore.Load(folder);Need(state.active.version=="0.2.0"&&state.previous.version=="0.3.0"&&File.Exists(UpdateStore.PathFor(folder,state.previous)),"Rollback destroyed version");});
            Test("saved paths cannot redirect launcher outside its version directory",delegate {string folder=Dir("bad-state");var old=UpdateStore.Capture(folder,fixture,"0.2.0");old.path="../unrelated.exe";UpdateStore.Save(folder,new LauncherState{active=old});Reject(delegate{UpdateStore.Load(folder);});});
            Test("actual headless child probe validates version and bounded output",delegate {string folder=Dir("probe");string child=Path.Combine(folder,"Fixture.exe");File.Copy(fixture,child);var expected=new ReleasePlan{Version="0.3.0",PayloadSha256=new string('a',64)};UpdateStore.Probe(child,folder,expected,CancellationToken.None);File.WriteAllText(Path.Combine(folder,"fixture-mode.txt"),"wrong-version");Reject(delegate{UpdateStore.Probe(child,folder,expected,CancellationToken.None);});File.WriteAllText(Path.Combine(folder,"fixture-mode.txt"),"flood");bool rejected=false;try{UpdateStore.Probe(child,folder,expected,CancellationToken.None);}catch(Exception){rejected=true;}Need(rejected,"Unbounded probe output accepted");});
            Test("canceling a child probe terminates only that test child",delegate {string folder=Dir("probe-cancel");string child=Path.Combine(folder,"Fixture.exe");File.Copy(fixture,child);File.WriteAllText(Path.Combine(folder,"fixture-mode.txt"),"sleep");using(var c=new CancellationTokenSource()){c.CancelAfter(200);try{UpdateStore.Probe(child,folder,new ReleasePlan{Version="0.3.0",PayloadSha256=new string('a',64)},c.Token);throw new Exception("Probe cancellation failed");}catch(OperationCanceledException){}}});
            Test("actual restart handshake commits before child proceeds",delegate {string folder=Dir("restart");Need(UpdateStore.StartReady(fixture,folder,Guard.HashFile(fixture)),"Restart failed");var timer=Stopwatch.StartNew();while(!File.Exists(Path.Combine(folder,"fixture-restarted.txt"))&&timer.ElapsedMilliseconds<3000)Thread.Sleep(20);Need(File.Exists(Path.Combine(folder,"fixture-restarted.txt")),"Child did not receive commit");});
            Test("bad restart hash or immediate child failure never commits",delegate {string folder=Dir("restart-bad");string child=Path.Combine(folder,"Fixture.exe");File.Copy(fixture,child);File.WriteAllText(Path.Combine(folder,"fixture-mode.txt"),"wrong-hash");Need(!UpdateStore.StartReady(child,folder,Guard.HashFile(child)),"Wrong handshake accepted");File.WriteAllText(Path.Combine(folder,"fixture-mode.txt"),"exit");Need(!UpdateStore.StartReady(child,folder,Guard.HashFile(child)),"Failed child accepted");Need(Directory.GetFiles(folder,"*.commit").Length==0,"Bad restart committed");});
        }
        // Seed only this isolated test installation. A live game must not prevent
        // shortcut tests; production registration and active-game guards are unchanged.
        private static void ShortcutTests(){
            Test("actual Desktop and Start Menu links target persistent launcher with installation args",delegate {string folder=Dir("links/install"),desktop=Dir("links/Desktop"),programs=Dir("links/Programs");UpdateStore.Save(folder,new LauncherState{active=UpdateStore.Capture(folder,UpdateStore.CurrentExe,UpdateBuild.Version)});UpdateStore.EnsureCurrent(folder);string stable=LauncherShortcuts.EnsureStable(folder);string initialHash=Guard.HashFile(stable);LauncherShortcuts.Apply(folder,true,true,desktop,programs);foreach(string link in new[]{Path.Combine(desktop,"Super Rocket 64.lnk"),Path.Combine(programs,"Super Rocket 64","Super Rocket 64.lnk")}){string[] actual=LauncherShortcuts.Read(link);Need(String.Equals(actual[0],stable,StringComparison.OrdinalIgnoreCase)&&actual[1]=="--install-dir "+Commands.Quote(folder)&&String.Equals(actual[2],folder,StringComparison.OrdinalIgnoreCase),"Wrong shortcut");}LauncherShortcuts.EnsureStable(folder);Need(Guard.HashFile(stable)==initialHash,"Stable launcher overwritten");string save=Path.Combine(folder,"data");Directory.CreateDirectory(save);File.WriteAllText(Path.Combine(save,"user.sav"),"KEEP");LauncherShortcuts.Apply(folder,false,false,desktop,programs);Need(!File.Exists(Path.Combine(desktop,"Super Rocket 64.lnk"))&&!Directory.Exists(Path.Combine(programs,"Super Rocket 64"))&&File.ReadAllText(Path.Combine(save,"user.sav"))=="KEEP"&&File.Exists(stable),"Shortcut removal changed data");});
            Test("unrelated shortcut and corrupt persistent launcher are preserved and rejected",delegate {string desktop=Dir("unrelated/Desktop"),programs=Dir("unrelated/Programs"),first=Dir("unrelated/first"),second=Dir("unrelated/second");LauncherShortcuts.Apply(first,true,false,desktop,programs);string link=Path.Combine(desktop,"Super Rocket 64.lnk"),before=Guard.HashFile(link);Reject(delegate{LauncherShortcuts.Apply(second,true,false,desktop,programs);});Need(Guard.HashFile(link)==before,"Unrelated shortcut overwritten");File.WriteAllText(LauncherShortcuts.StablePath(first),"changed");Reject(delegate{LauncherShortcuts.EnsureStable(first);});Need(File.ReadAllText(LauncherShortcuts.StablePath(first))=="changed","Tampered entry overwritten");});
        }
        [STAThread] internal static int Main(string[] args){root=Path.GetFullPath(args[0]);fixture=Path.GetFullPath(args[1]);Directory.CreateDirectory(root);try{MetadataTests();StateTests();ShortcutTests();Console.WriteLine("PASS "+passed+" updater checks; test child processes and isolated shortcut folders only; no gameplay or foreground UI.");return 0;}catch(Exception error){Console.Error.WriteLine(error);return 1;}}
    }
}
