/* Actual source bodies generated by extract_enemy_native.py. Only world,
 * sound, RNG and outgoing-policy services below are fixture stubs. */
#include "sm64.h"
#include "behavior_data.h"
#include "object_constants.h"
#include "object_fields.h"
#include "game/object_helpers.h"
#include "game/obj_behaviors.h"
#include "game/obj_behaviors_2.h"
#include "game/object_list_processor.h"
#include "game/interaction.h"
#include "game/behavior_actions.h"
#include "game/spawn_sound.h"
#include "game/rocket_enemy.h"
#include "game/rng_position.h"
#include "engine/math_util.h"
#include "engine/surface_collision.h"
#include "audio/external.h"
#include "pc/network/network.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>
struct Object *gCurrentObject;
static struct Object target,parent,spawned[32];
static int coins,explosions,respawners,spawns;
static u8 respawnBits;
const BehaviorScript bhvSingleCoinGetsSpawned[]={1},bhvMovingYellowCoin[]={2},bhvMrIBlueCoin[]={3},bhvExplosion[]={4},bhvBobomb[]={5};
const BehaviorScript bhvSmallWhomp[]={6};
static int managed,coinSends;
static struct SyncObject coinSync;
int boss_net_managed(const struct Object *obj){(void)obj;return managed;}
int boss_net_simulates(const struct Object *obj){(void)obj;return managed;}
struct SyncObject *sync_object_init(struct Object *coin,f32 distance){assert(distance==SYNC_DISTANCE_ONLY_EVENTS);coin->oSyncID=4096+coinSends+1;return &coinSync;}
void sync_object_init_field_with_size(struct Object *coin,void *field,u8 size){assert(field==&coin->activeFlags&&size==sizeof(coin->activeFlags));}
void network_send_spawn_objects(struct Object *objects[],u32 models[],u8 count){
    assert(count==1&&models[0]==MODEL_YELLOW_COIN&&objects[0]->oSyncID>=4096&&coinSync.fullObjectSync);coinSends++;
}
#define o gCurrentObject
int rocket_enemy_attack(struct Object *obj){assert(obj==o);return 0;}
int rocket_contacts_bobomb_yaw(struct Object *obj,s16 *yaw){(void)obj;(void)yaw;return 0;}
void network_send_object_reliability(struct Object *obj,bool reliable){(void)obj;(void)reliable;assert(0);}
void network_coin_boost_init_identity(struct Object *obj){(void)obj;}
void cur_obj_become_tangible(void){o->oIntangibleTimer=0;}
void cur_obj_become_intangible(void){o->oIntangibleTimer=-1;}
void cur_obj_hide(void){o->header.gfx.node.flags|=GRAPH_RENDER_INVISIBLE;}
struct Object *spawn_object(struct Object *obj,s32 model,const BehaviorScript *behavior){
    assert(obj==o);(void)model;assert(spawns<32);
    if(behavior==bhvSingleCoinGetsSpawned||behavior==bhvMovingYellowCoin)coins++;
    if(behavior==bhvExplosion)explosions++;
    return &spawned[spawns++];
}
f32 find_floor(f32 x,f32 y,f32 z,struct Surface **floor){(void)x;(void)y;(void)z;*floor=NULL;return 0;}
void obj_translate_xz_random(struct Object *obj,f32 range){(void)obj;(void)range;}
void spawn_mist_particles(void){}
void spawn_mist_particles_with_sound(u32 sound){(void)sound;}
void create_sound_spawner(s32 sound){(void)sound;}
void cur_obj_play_sound_2(s32 sound){(void)sound;}
void cur_obj_scale(f32 scale){(void)scale;}
void cur_obj_update_floor_and_walls(void){}
void cur_obj_extend_animation_if_at_end(void){}
void cur_obj_move_standard(s16 slope){(void)slope;}
s32 obj_die_if_above_lava_and_health_non_positive(void){return 0;}
struct Object *nearest_player_to_object(struct Object *obj){(void)obj;return NULL;}
s16 obj_angle_to_object(struct Object *a,struct Object *b){(void)a;(void)b;return 0;}
void obj_set_squished_action(void){assert(0);}
void shelled_koopa_attack_handler(s32 attack){(void)attack;assert(0);}
void obj_set_speed_to_zero(void){assert(0);}
void wiggler_jumped_on_attack_handler(void){assert(0);}
void huge_goomba_weakly_attacked(void){assert(0);}
s32 obj_attack_collided_from_other_object(struct Object *obj){(void)obj;return 0;}
void create_respawner(s32 model,const BehaviorScript *behavior,s32 distance){
    assert(model==MODEL_BLACK_BOBOMB&&behavior==bhvBobomb&&distance==3000);respawners++;
}
void set_object_respawn_info_bits(struct Object *obj,u8 bits){assert(obj==o||obj==&parent);respawnBits|=bits;}
void rng_position_init(f32 x,f32 y,f32 z){(void)x;(void)y;(void)z;}
void rng_position_finish(void){}
f32 random_float(void){return .5f;}
u16 random_u16(void){return 0;}
#include "enemy_native_bodies.inc"
static void fresh(void){
    memset(&target,0,sizeof target);memset(&parent,0,sizeof parent);memset(spawned,0,sizeof spawned);
    o=&target;target.activeFlags=ACTIVE_FLAG_ACTIVE;target.header.gfx.scale[0]=target.header.gfx.scale[1]=target.header.gfx.scale[2]=1;
    coins=explosions=respawners=spawns=respawnBits=0;
    target.oInteractStatus=INT_STATUS_INTERACTED|INT_STATUS_WAS_ATTACKED|ATTACK_FAST_ATTACK;
}
int main(void){
    fresh();o->parentObj=&parent;o->oBehParams2ndByte=4;
    assert(obj_handle_attacks(&sGoombaHitbox,GOOMBA_ACT_ATTACKED_MARIO,sGoombaAttackHandlers[0])==ATTACK_FAST_ATTACK);
    mark_goomba_as_dead();assert(o->oAction==OBJ_ACT_VERTICAL_KNOCKBACK&&!coins&&o->oVelY==50);
    assert(parent.oBehParams==256&&respawnBits==1);
    o->oTimer=8;obj_act_knockback(1);assert(!coins&&o->activeFlags==ACTIVE_FLAG_ACTIVE);
    o->oTimer=9;obj_act_knockback(1);assert(coins==1&&o->oNumLootCoins==0&&!o->activeFlags);
    obj_die_if_health_non_positive();assert(coins==1); // native loot decrement prevents duplicate coin
    struct ObjectHitbox *immediate[]={&sSkeeterHitbox,&sSnufitHitbox,&sFlyGuyHitbox};
    for(unsigned i=0;i<sizeof immediate/sizeof immediate[0];i++){
        fresh();assert(obj_check_attacks(immediate[i],0)==ATTACK_FAST_ATTACK);
        assert(!o->activeFlags&&coins==immediate[i]->numLootCoins);obj_die_if_health_non_positive();assert(coins==immediate[i]->numLootCoins);
    }
    struct ObjectHitbox *direct[]={&sSpindriftHitbox,&sScuttlebugHitbox};
    for(unsigned i=0;i<sizeof direct/sizeof direct[0];i++){
        fresh();cur_obj_set_hitbox_and_die_if_attacked(direct[i],0,0);
        assert(!o->activeFlags&&coins==direct[i]->numLootCoins);
        cur_obj_set_hitbox_and_die_if_attacked(direct[i],0,0);assert(coins==direct[i]->numLootCoins);
    }
    fresh();cur_obj_set_hitbox_and_die_if_attacked(&sScuttlebugHitbox,0,1);assert(!coins&&!o->activeFlags);
    fresh();o->oInteractStatus=INT_STATUS_INTERACTED|INT_STATUS_WAS_ATTACKED|INT_STATUS_TOUCHED_BOB_OMB;
    bobomb_check_interactions();assert(o->oAction==BOBOMB_ACT_EXPLODE&&!o->oInteractStatus&&!coins);
    for(int timer=0;timer<6;timer++){o->oTimer=timer;bobomb_act_explode();if(timer<5)assert(!coins&&!explosions);}
    assert(!o->activeFlags&&coins==1&&explosions==1&&respawners==1&&respawnBits==1);
    bobomb_spawn_coin();assert(coins==1); // native one-coin bit survives duplicate request
    fresh();target.behavior=bhvSmallWhomp;target.oNumLootCoins=5;managed=1;coinSends=0;
    obj_spawn_loot_yellow_coins(&target,5,20);assert(coins==5&&coinSends==5&&target.oNumLootCoins==0);
    obj_spawn_loot_yellow_coins(&target,5,20);assert(coins==5&&coinSends==5);
    managed=0;
    puts("enemy native source: Goomba knockback/death/spawner bit, seven enemy reward paths and duplicate-coin guards passed (host services stubbed)");
    return 0;
}
