/* Production functions generated by extract_vanish_native.py. Geometry, audio,
 * network delivery and save storage are explicit inert fixture services. */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include "sm64.h"
#include "behavior_data.h"
#include "game/behavior_actions.h"
#include "game/hardcoded.h"
#include "game/interaction.h"
#include "game/save_file.h"
#include "game/rocket_adapter.h"
#include "game/rocket_caps.h"
#include "pc/rocket_runtime.h"
#include "seq_ids.h"
#include "sounds.h"
#include "audio/external.h"
struct MarioState gMarioStates[MAX_PLAYERS];
struct LevelValues gLevelValues;
struct BehaviorValues gBehaviorValues;
static struct Object object,playerObject;
static struct Object *fixtureObject=&object;
static u32 saveFlags;
static int capSwitchForcePress,press,boxHit,sends,collects,nearest=1,stops,fades;
static int managedCap;
/* Explicit offline service boundary; real host grants and deduplication are
 * covered by test_wing.c. These stubs never mutate flags, timer or pickup. */
int rocket_caps_interact(struct MarioState *m,struct Object *obj){(void)m;(void)obj;return 0;}
int rocket_caps_managed(const struct MarioState *m){(void)m;return managedCap;}
int rocket_runtime_owns_controls(void){return 0;}
static s32 D_8032F0C0[]={SAVE_FLAG_HAVE_WING_CAP,SAVE_FLAG_HAVE_METAL_CAP,SAVE_FLAG_HAVE_VANISH_CAP};
static struct ObjectHitbox sExclamationBoxHitbox;
const BehaviorScript bhvNormalCap[]={0},bhvMetalCap[]={1},bhvWingCap[]={2},bhvVanishCap[]={3},bhvRotatingExclamationMark[]={4};
u32 save_file_get_flags(void){return saveFlags;}
void save_file_set_flags(u32 flags){saveFlags|=flags;}
static int cur_obj_is_mario_on_platform(void){return 0;}
int rocket_adapter_vanish_switch_contact(struct Object *obj){assert(obj==fixtureObject);return press;}
int rocket_adapter_vanish_box_contact(struct Object *obj){assert(obj==fixtureObject);return boxHit;}
static void cur_obj_play_sound_2(int sound){(void)sound;}
static void network_send_object(struct Object *obj){assert(obj==fixtureObject);sends++;}
static void cur_obj_become_intangible(void){fixtureObject->oIntangibleTimer=-1;}
static void cur_obj_become_tangible(void){fixtureObject->oIntangibleTimer=0;}
static void cur_obj_unhide(void){}
static void cur_obj_set_model(int model){(void)model;}
static int cur_obj_was_attacked_or_ground_pounded(void){return 0;}
static void obj_set_hitbox(struct Object *obj,struct ObjectHitbox *hitbox){(void)obj;(void)hitbox;}
static int smlua_model_util_load_dummy(int model){return model;}
#define smlua_model_util_load smlua_model_util_load_dummy
static void spawn_object(struct Object *obj,int model,const BehaviorScript *behavior){(void)obj;(void)model;(void)behavior;}
static struct MarioState *nearest_mario_state_to_object(struct Object *obj){(void)obj;return &gMarioStates[nearest?0:1];}
static void queue_rumble_data_object(struct Object *obj,int a,int b){(void)obj;(void)a;(void)b;}
static void load_object_collision_model(void){}
void *virtual_to_segmented(u32 segment,const void *behavior){(void)segment;return (void*)behavior;}
static const BehaviorScript *smlua_override_behavior(const BehaviorScript *behavior){return behavior;}
static void set_mario_action(struct MarioState *m,u32 action,u32 arg){m->action=action;m->actionArg=arg;}
void play_sound(s32 sound,float *position){(void)sound;(void)position;}
void play_character_sound(struct MarioState *m,enum CharacterSound sound){(void)m;(void)sound;}
static void play_cap_music(u16 music){(void)music;}
static void network_send_collect_item(struct Object *obj){assert(obj==fixtureObject);collects++;}
static void stop_cap_music(void){stops++;}
static void fadeout_cap_music(void){fades++;}

/* Native behavior files use the engine's current-object shorthand. Function
 * arguments called o in interaction.c must remain ordinary C identifiers. */
#define o fixtureObject
#include "native_vanish_behaviors.inc"
#undef o
#include "native_vanish_interactions.inc"

int main(void){
    object.oBehParams2ndByte=2;exclamation_box_act_0();assert(object.oAction==1&&!saveFlags);
    boxHit=1;exclamation_box_act_1();assert(object.oAction==1&&object.oIntangibleTimer==-1&&!saveFlags&&!sends);
    object.oAction=1;cap_switch_act_1();assert(object.oAction==1&&!saveFlags);
    press=1;cap_switch_act_1();assert(object.oAction==2&&saveFlags==SAVE_FLAG_HAVE_VANISH_CAP&&sends==1);
    assert(!capSwitchForcePress);press=0; // Native event field is transient.
    object.oAction=1;exclamation_box_act_1();assert(object.oAction==2);
    object.oTimer=1;object.oIntangibleTimer=0;nearest=0;exclamation_box_act_2();assert(object.oAction==2&&sends==1);
    nearest=1;exclamation_box_act_2();assert(object.oAction==3&&sends==2&&object.oIntangibleTimer==-1);
    assert(saveFlags==SAVE_FLAG_HAVE_VANISH_CAP&&!gMarioStates[0].flags);
    struct MarioState *m=&gMarioStates[0];m->marioObj=&playerObject;m->health=0x880;m->action=ACT_IDLE;
    object.behavior=bhvVanishCap;gLevelValues.vanishCapDuration=600;
    assert(!interact_cap(&gMarioStates[1],INTERACT_CAP,&object)&&!collects);
    assert(interact_cap(m,INTERACT_CAP,&object)&&collects==1);
    assert(m->capTimer==600&&(m->flags&MARIO_VANISH_CAP)&&m->action==ACT_PUTTING_ON_CAP);
    managedCap=1;update_and_return_cap_flags(m);assert(m->capTimer==600);
    managedCap=0; // Shared timers stay untouched; offline native timer follows.
    m->action=ACT_READING_AUTOMATIC_DIALOG;update_and_return_cap_flags(m);assert(m->capTimer==600);
    m->action=ACT_IDLE;assert(update_and_return_cap_flags(m)&MARIO_VANISH_CAP);assert(m->capTimer==599);
    m->capTimer=61;update_and_return_cap_flags(m);assert(m->capTimer==60&&fades==1);
    m->action=ACT_READING_NPC_DIALOG;update_and_return_cap_flags(m);assert(m->capTimer==59);
    m->capTimer=1;update_and_return_cap_flags(m);assert(!m->capTimer&&!(m->flags&MARIO_SPECIAL_CAPS)&&stops==1);
    assert(saveFlags==SAVE_FLAG_HAVE_VANISH_CAP); // Expiry never undoes progression.
    puts("Native cap source: locked outline, switch save flag/event, unlocked box, owner pickup, native timer/dialog/fade/expiry passed (inert services)");
}
