#!/usr/bin/env python3
"""Validate a local original BM64 US ROM and prepare private research chunks.

This is not a model converter, playable character, ROM downloader, patcher,
recompiler, or launcher. No external programs or third-party modules are run.
The original input is opened read-only. Generated bytes must stay private.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import stat
import struct
import sys
import zlib

METADATA = Path(__file__).with_name("bm64_us_10_metadata.json")
ROM_SIZE = 8 * 1024 * 1024
MAX_DECODED = 1024 * 1024
EXPECTED_SHA1 = "8a7648d8105ac4fc1ad942291b2ef89aeca921c9"
EXPECTED_MD5 = "093058ece14c8cc1a887b2087eb5cfe9"
EXPECTED_DECOMP_SHA1 = "8f9e1706b5ef0d51c3cbce4a024796f56420784a"
EXPECTED_DECOMP_MD5 = "d2f9313cccae0af85d23ac37666c0173"


class InputError(ValueError):
    pass


def normalize(data: bytes) -> tuple[bytes, str]:
    """Normalize N64 byte ordering by magic, never by filename extension."""
    if len(data) != ROM_SIZE:
        raise InputError(f"Expected an 8,388,608-byte original retail ROM; got {len(data):,} bytes")
    magic = data[:4]
    if magic == b"\x80\x37\x12\x40":
        return data, "z64"
    if magic == b"\x37\x80\x40\x12":
        result = bytearray(len(data))
        result[0::2], result[1::2] = data[1::2], data[0::2]
        return bytes(result), "v64"
    if magic == b"\x40\x12\x37\x80":
        result = bytearray(len(data))
        for index in range(4):
            result[index::4] = data[3 - index::4]
        return bytes(result), "n64"
    raise InputError("Unrecognized N64 header; ZIPs, copier headers and arbitrary files are not accepted")


def validate(data: bytes) -> tuple[bytes, dict]:
    rom, order = normalize(data)
    sha1 = hashlib.sha1(rom).hexdigest()
    md5 = hashlib.md5(rom).hexdigest()
    if sha1 != EXPECTED_SHA1 or md5 != EXPECTED_MD5:
        raise InputError("Unsupported ROM. Required: original Bomberman 64 (1997), USA 1.0; "
                         f"normalized SHA-1 {EXPECTED_SHA1}. Actual SHA-1: {sha1}")
    return rom, {"profile": "bm64-us-1.0", "size": len(rom), "input_byte_order": order,
                 "normalized_sha1": sha1, "normalized_md5": md5,
                 "normalized_crc32": f"{zlib.crc32(rom):08x}"}


def read_rom(path: Path) -> bytes:
    # A size limit also prevents reading special streams and unexpectedly huge files.
    before = path.stat()
    if not stat.S_ISREG(before.st_mode) or before.st_size != ROM_SIZE:
        raise InputError("Input must be a regular 8,388,608-byte local retail ROM")
    # O_NONBLOCK closes the stat/open FIFO race on POSIX. O_BINARY preserves
    # exact ROM bytes on Windows. Neither flag changes normal file semantics.
    descriptor = os.open(path, os.O_RDONLY | getattr(os, "O_NONBLOCK", 0) | getattr(os, "O_BINARY", 0))
    with os.fdopen(descriptor, "rb") as source:
        info = os.fstat(source.fileno())
        if not stat.S_ISREG(info.st_mode) or info.st_size != ROM_SIZE:
            raise InputError("Input must be a regular 8,388,608-byte local retail ROM")
        if info.st_dev != before.st_dev or info.st_ino != before.st_ino:
            raise InputError("ROM file changed during opening")
        data = source.read(ROM_SIZE + 1)
    if len(data) != ROM_SIZE:
        raise InputError("ROM size changed during reading")
    return data


def decode_lzss(source: bytes, expected_size: int) -> bytes:
    """Bounded BM64 1024-byte-ring LZSS decoder, matching the inspected format.

    Four-byte BE decoded length; flags consumed least-significant-bit first.
    A set bit emits one literal. A clear bit has a 10-bit absolute ring offset
    and six-bit length + 3. The zero-filled ring begins writing at 958.
    This follows the file-format facts in the pinned decomp tool; all sizes,
    reads and writes are checked rather than trusting a file's length header.
    """
    if not isinstance(expected_size, int) or not 1 <= expected_size <= MAX_DECODED:
        raise InputError("Decoded size is outside the bounded research profile")
    if len(source) < 4 or struct.unpack_from(">I", source)[0] != expected_size:
        raise InputError("Compressed length header does not match the pinned profile")
    result = bytearray()
    ring = bytearray(1024)
    write = 958
    cursor = 4
    flags = remaining = 0
    while len(result) < expected_size:
        if not remaining:
            if cursor >= len(source):
                raise InputError("Truncated compression flag")
            flags, remaining = source[cursor], 8
            cursor += 1
        if flags & 1:
            if cursor >= len(source):
                raise InputError("Truncated literal")
            value = source[cursor]
            cursor += 1
            result.append(value)
            ring[write] = value
            write = (write + 1) & 1023
        else:
            if cursor + 2 > len(source):
                raise InputError("Truncated match")
            low, high = source[cursor:cursor + 2]
            cursor += 2
            read = low | ((high & 0xC0) << 2)
            length = (high & 0x3F) + 3
            if len(result) + length > expected_size:
                raise InputError("Match overruns the declared decoded length")
            for _ in range(length):
                value = ring[read]
                result.append(value)
                ring[write] = value
                read = (read + 1) & 1023
                write = (write + 1) & 1023
        flags >>= 1
        remaining -= 1
    # Stored ranges may contain alignment bytes. Full-ROM and reconstructed
    # digests, rather than assumed padding values, authenticate those bytes.
    return bytes(result)


def load_metadata() -> dict:
    metadata = json.loads(METADATA.read_text(encoding="utf-8"))
    if metadata.get("schema_version") != 1 or metadata.get("profile") != "bm64-us-1.0":
        raise InputError("Unsupported research metadata profile")
    if metadata["retail"]["sha1"] != EXPECTED_SHA1 or len(metadata["overlays"]) != 109:
        raise InputError("Research metadata identity mismatch")
    names = set()
    position = ROM_SIZE
    for entry in metadata["overlays"]:
        name = entry["name"]
        if not isinstance(name, str) or not name or any(c not in "abcdefghijklmnopqrstuvwxyz0123456789_" for c in name) or name in names:
            raise InputError("Unsafe or duplicated research chunk name")
        names.add(name)
        for key in ("rom_offset", "stored_size", "decoded_size", "decomp_offset", "table_rom", "entry_offset"):
            if type(entry[key]) is not int or entry[key] < 0:
                raise InputError("Invalid research chunk integer")
        if type(entry["compressed"]) is not bool:
            raise InputError("Invalid compression marker")
        if entry["rom_offset"] + entry["stored_size"] > ROM_SIZE or entry["stored_size"] == 0:
            raise InputError("Research chunk exceeds retail ROM bounds")
        if not 1 <= entry["decoded_size"] <= MAX_DECODED or entry["decomp_offset"] != position:
            raise InputError("Invalid reconstructed chunk range")
        if entry["rom_offset"] != entry["table_rom"] + 0x2008 + entry["entry_offset"]:
            raise InputError("Research chunk address disagrees with table")
        position += entry["decoded_size"]
    if position != metadata["decomp_expected"]["size"]:
        raise InputError("Reconstructed size mismatch")
    return metadata


def research_chunks(rom: bytes, metadata: dict) -> list[tuple[str, bytes, dict]]:
    """Decode only after validation; never create a patched/full output ROM."""
    if len(rom) != ROM_SIZE or hashlib.sha1(rom).hexdigest() != EXPECTED_SHA1:
        raise InputError("Research extraction requires the validated original ROM")
    result = []
    digest = hashlib.sha1(rom)
    md5 = hashlib.md5(rom)
    for entry in metadata["overlays"]:
        start = entry["rom_offset"]
        stored = rom[start:start + entry["stored_size"]]
        if entry["compressed"]:
            decoded = decode_lzss(stored, entry["decoded_size"])
        else:
            decoded = stored + bytes((-len(stored)) & 15)
        if len(decoded) != entry["decoded_size"]:
            raise InputError("Decoded chunk size mismatch")
        result.append((entry["name"] + ".bin", decoded, entry))
        digest.update(decoded)
        md5.update(decoded)
    if digest.hexdigest() != EXPECTED_DECOMP_SHA1 or md5.hexdigest() != EXPECTED_DECOMP_MD5:
        raise InputError("Original overlay reconstruction failed the pinned decomp digests; no outputs written")
    # Main actor/engine code is an original uncompressed region, not a model.
    result.insert(0, ("main_code.bin", rom[0x40000:0xBFB00],
                      {"rom_offset": 0x40000, "vram": 0x80225800, "decoded_size": 0x7FB00}))
    return result


def write_private(output: Path, identity: dict, chunks: list[tuple[str, bytes, dict]]) -> dict:
    # Reject redirected paths, including dangling links. mkdir must be exclusive;
    # this tool never replaces a previous extraction, input, save or user folder.
    output = output.absolute()
    if ".." in output.parts:
        raise InputError("Output must not contain parent-directory traversal")
    if output.exists() or output.is_symlink():
        raise InputError("Output already exists; choose a new private directory")
    for ancestor in output.parents:
        info = ancestor.lstat()
        if stat.S_ISLNK(info.st_mode) or getattr(info, "st_file_attributes", 0) & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400):
            raise InputError("Output ancestors must not be symlinks or Windows reparse points")
    if not output.parent.is_dir():
        raise InputError("Output parent must already exist")
    manifest = {"schema_version": 1, "kind": "bm64-original-code-research", "identity": identity,
                "playable": False, "model_decoded": False, "mechanics_verified": False,
                "reconstructed_sha1": EXPECTED_DECOMP_SHA1, "files": []}
    output.mkdir(mode=0o700)
    # Ignore is written first; manifest last means interrupted work cannot be
    # mistaken for a complete preparation. Partial results remain private.
    with (output / ".gitignore").open("x", encoding="utf-8") as handle:
        handle.write("*\n")
    for name, data, origin in chunks:
        if Path(name).name != name or name in (".", ".."):
            raise InputError("Unsafe chunk output name")
        with (output / name).open("xb") as handle:
            handle.write(data)
        manifest["files"].append({"path": name, "size": len(data),
                                  "sha256": hashlib.sha256(data).hexdigest(), "origin": origin})
    with (output / "manifest.json").open("x", encoding="utf-8") as handle:
        json.dump(manifest, handle, indent=2)
        handle.write("\n")
    return manifest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("rom", type=Path, help="Your original local BM64 USA 1.0 ROM")
    parser.add_argument("--output", type=Path, help="New private directory for original code research chunks")
    args = parser.parse_args(argv)
    try:
        rom, identity = validate(read_rom(args.rom))
        if args.output:
            metadata = load_metadata()
            chunks = research_chunks(rom, metadata)
            result = write_private(args.output, identity, chunks)
            print(json.dumps({"status": "prepared-for-research", "identity": identity,
                              "files": len(result["files"]), "playable": False}, indent=2))
        else:
            print(json.dumps({"status": "supported-original-rom", "identity": identity,
                              "playable": False, "files_written": 0}, indent=2))
        return 0
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f"Bomberman 64 preparation stopped: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
